controller_list:
  - name: fake_ur3_controller
    joints:
      - ur3_arm_shoulder_pan_joint
      - ur3_arm_shoulder_lift_joint
      - ur3_arm_elbow_joint
      - ur3_arm_wrist_1_joint
      - ur3_arm_wrist_2_joint
      - ur3_arm_wrist_3_joint
  - name: fake_EndEffector_controller
    joints:
      []